### ISSUE TITLE
Too many call to the token exchange endpoint when uploading file to GCS

### ISSUE THREAD

**Issue by GregoireW** [googleapis/google-auth-library-nodejs#1836]
Hello,

This issue is linked to https://github.com/google-github-actions/upload-cloud-storage/issues/364

The issue is  when we use the  `google-github-actions/upload-cloud-storage`  action, this authentication library is used and we end up with a huge number of call on the token exchange API.

![image](https://github.com/user-attachments/assets/3dae668e-af76-417f-9499-d318bb5d7d56)

As this is rate limited, we got some spike that made some things worst. I already increase the api quota, but to fix our issue it would need a crazy number.  It is better to fix this here.

To repoduce the issue, you can run an action containing:

```
    - uses: actions/checkout@v4
        id: checkout

      - name: generate
        run: |
          mkdir site
          for i in {1..250} ; do 
            head -c 1M </dev/urandom > site/test-$i.txt ; 
          done;

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          service_account: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

      - name: Publish report
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./site
          destination: zzzzzzzzzzzzzzzzzzzzz
          parent: false
          process_gcloudignore: false
          gzip: false
```
