### ISSUE TITLE
Project ID detection does not work in local docker container

### ISSUE THREAD

**Issue by itmayziii** [googleapis/google-auth-library-nodejs#896]
#### Environment details

  - OS: Mac OS 10.15.3 (19D76)
  - Node.js version: v12.15.0
  - npm version: 6.13.4
  - `google-auth-library` version: 5.9.2

#### Steps to reproduce

1. Create a docker-compose.yaml file with a nodejs app, something like
```
version: "3.7"
services:
  app:
    container_name: app
    image: node:12
    working_dir: /home/node/app
    command: ["npm", "run", "start"]
    ports:
      - 4000:4000
    volumes:
      - ./:/home/node/app
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      NODE_ENV: "development"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/.config/gcloud/application_default_credentials.json"
```

2. In your code include the use of one of the google SDKs
```typescript
import { Storage } from '@google-cloud/storage'
export const storage = new Storage()
```

3. Use the docker-compose file to start up your app `docker-compose up`

4. See error Error: Unable to detect a Project Id in the current environment.

If I hardcode a project ID  like `new Storage({projectId: 'test'})`  then it works so that tells me my application_default_credentials.json file is being read successfully, but whatever method we are using to detect a project ID does not work with the official NodeJS docker image.
